In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
# Load dataset
df = pd.read_csv("/content/1) iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
# Handle missing values
df.fillna(df.mean(numeric_only=True), inplace=True)

In [ ]:
# Encode categorical columns
for col in df.select_dtypes(include='object').columns:
    df[col] = LabelEncoder().fit_transform(df[col])

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
# Split features & target
X = df.drop("species", axis=1)
y = df["species"]

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Normalize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print("Preprocessing Done")

Preprocessing Done

In [ ]:
# Convert arrays back to DataFrames
X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)

# Add target column
train_df = X_train_df.copy()
train_df["target"] = y_train.values
train_df["split"] = "train"

test_df = X_test_df.copy()
test_df["target"] = y_test.values
test_df["split"] = "test"

# Combine
final_df = pd.concat([train_df, test_df], ignore_index=True)

# Save
final_df.to_csv("/content/iris_dataset_with_split.csv", index=False)

In [ ]:
final_df.head()

   sepal_length  sepal_width  petal_length  petal_width  target  split
0     -1.348900     0.337078     -1.368230    -1.284566       0  train
1      0.820589    -0.582226      0.470938     0.393762       1  train
2      0.579535     0.566904      1.251192     1.684783       2  train
3     -1.107846    -1.271704      0.415206     0.651966       2  train
4     -1.469427     0.107252     -1.256765    -1.284566       0  train

------------------------------------------------------------------

Part-2

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load dataset
df = pd.read_csv("/content/2) Stock Prices Data Set.csv")

# Handle missing values
df.fillna(df.mean(numeric_only=True), inplace=True)

# Encode categorical columns
for col in df.select_dtypes(include='object').columns:
    df[col] = LabelEncoder().fit_transform(df[col])

In [16]:
df.head()

   symbol  date      open      high       low     close    volume
0       1     0   25.0700   25.8200   25.0600   25.3600   8998943
1       3     0   79.3828   79.5756   78.8601   79.0185  58791957
2       2     0  110.3600  111.8800  109.2900  109.7400    542711
3       4     0   52.1200   52.3300   51.5200   51.9800   4569061
4       5     0   70.1100   70.2300   69.4800   69.8900   1148391

In [17]:
# Split features & target
X = df.drop("volume", axis=1)
y = df["volume"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Normalize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Preprocessing Done")

Preprocessing Done

In [18]:
# Convert arrays back to DataFrames
X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)

# Add target column
train_df = X_train_df.copy()
train_df["target"] = y_train.values
train_df["split"] = "train"

test_df = X_test_df.copy()
test_df["target"] = y_test.values
test_df["split"] = "test"

# Combine
final_df = pd.concat([train_df, test_df], ignore_index=True)

# Save
final_df.to_csv("/content/Stock_Prices_dataset_with_split.csv", index=False)

------------------------------------------------------------------

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
# Load dataset
df = pd.read_csv("/content/3) Sentiment dataset.csv")
df.head(2)

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8

In [30]:
df.drop(columns=["Unnamed: 0.1", "Unnamed: 0"], inplace=True)
df.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 85.9+ KB

In [35]:
df.dropna(subset=["Text", "Sentiment"], inplace=True)
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20.0,39.0,UK,2017,8,18,18
728,729,733,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,USA,2018,6,22,14
729,730,734,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,Canada,2019,4,5,17
730,731,735,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21.0,43.0,UK,2020,2,29,20
731,732,736,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,USA,2020,11,15,15

In [36]:
TEXT_COL = "Text"
TARGET_COL = "Sentiment"

le = LabelEncoder()
df[TARGET_COL] = le.fit_transform(df[TARGET_COL])

# ---------------------------
# 4. Train-test split
# ---------------------------
X_train, X_test, y_train, y_test = train_test_split(
    df[TEXT_COL],
    df[TARGET_COL],
    test_size=0.2,
    random_state=42
)

# ---------------------------
# 5. Text Vectorization (TF-IDF)
# ---------------------------
vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [37]:
# ---------------------------
# 6. Convert to DataFrame (optional for saving)
# ---------------------------
X_train_df = pd.DataFrame(X_train_vec.toarray())
X_test_df = pd.DataFrame(X_test_vec.toarray())

# ---------------------------
# 7. Save everything cleanly
# ---------------------------
# Add labels + split flag
train_df = X_train_df.copy()
train_df["target"] = y_train.values
train_df["split"] = "train"

test_df = X_test_df.copy()
test_df["target"] = y_test.values
test_df["split"] = "test"

final_df = pd.concat([train_df, test_df], ignore_index=True)

# Save dataset
final_df.to_csv("/content/final_sentiment_dataset.csv", index=False)



print("Preprocessing Complete. Dataset Saved.")

Preprocessing Complete. Dataset Saved.

--------------------------------------